
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    crd.netcracker.com/version: 0.0.18
    controller-gen.kubebuilder.io/version: v0.6.2
  creationTimestamp: null
  name: consulacls.netcracker.com
spec:
  group: netcracker.com
  names:
    kind: ConsulACL
    listKind: ConsulACLList
    plural: consulacls
    singular: consulacl
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            acl:
              properties:
                commonReconcile:
                  type: string
                json:
                  type: string
                name:
                  type: string
              required:
              - json
              - name
              type: object
          required:
          - acl
          type: object
        status:
          properties:
            bindRulesStatus:
              type: string
            generalStatus:
              type: string
            policiesStatus:
              type: string
            rolesStatus:
              type: string
          required:
          - policiesStatus
          type: object
      #Comment it if you deploy to Kubernetes 1.11 (e.g OpenShift 3.11)
      #type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
