{{- if eq (include "remove-tokens.enabled" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "consul.fullname" . }}-remove-tokens
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "consul.labels" . | indent 4 }}
{{ include "consul-service.defaultLabels" . | indent 4 }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - pods/binding
{{- end }}
